openapi: "3.0.3"

info:
  description: "
  Webcontroller Relay (Arduino) \n
  https://github.com/1e1/arduino-webcontroller-relay
  "
  version: "1.0.0"
  title: "WebController-Relay"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "2.71828183E0+github@gmail.com"

servers:
  - url: "https://webrelay.local:{port}/{basePath}"
    variables:
      port:
        default: "80"
      basePath:
        default: ""

paths:
  /cfg/g:      
    get:
      security:
        - basicAuth: []
      description: "read AP configuration"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CfgGlobal"
    post:
      security:
        - basicAuth: []
      description: "write AP configuration"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CfgGlobal"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CfgGlobal"

  /cfg/w:
    get:
      security:
        - basicAuth: []
      description: "read Wifi STAtions configuration"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CfgWifis"
    post:
      security:
        - basicAuth: []
      description: "write AP configuration"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CfgWifis"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CfgWifis"
  /cfg/r:
    get:
      description: "read relay configuration"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CfgRelays"
    post:
      security:
        - basicAuth: []
      description: "write AP configuration"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CfgRelays"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CfgRelays"
  /cfg/reboot:
    delete:
      security:
        - basicAuth: []
      description: "trigger a reboot"
      responses:
        204:
          description: "successful operation"
  /api/r:
    get:
      description: "read relay configuration"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CfgRelays"
  /api/r/{relayId}: # TODO
    parameters:
    - name: relayId
      in: path
      description: ID of the relay
      required: true
      schema:
        type: integer
        minimum: 0
        maximum: 127
    get:
      description: "read relay state"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImplRelay"
    put:
      description: "update relay state"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImplRelay"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImplRelay"

components:
  responses:
    204:
      description: "no content, usually because the request was lost while the device was waking up"
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    CfgGlobal:
      type: "object"
      description: "main configuration as Access Point"
      properties:
        d:
          description: "mDNS name"
          type: "string"
          minLength: 1
          maxLength: 32
        u:
          description: "username"
          type: "string"
          minLength: 1
          maxLength: 32
        w:
          description: "user password"
          type: "string"
          format: "password"
          minLength: 8
          maxLength: 63
        n:
          description: "wifi ssid"
          type: "string"
          minLength: 1
          maxLength: 32
        p:
          description: "wifi password"
          type: "string"
          format: "password"
          minLength: 8
          maxLength: 63
        c:
          description: "wifi channel"
          type: "integer"
          minimum: 1
          maximum: 13
        h:
          description: "is hidden wifi"
          type: "boolean"
        r:
          description: "ESP can auto restart"
          type: "boolean"
      example:
        d: "mDNS name"
        u: "myUsername"
        w: "myPassword"
        n: "myWifiSsid"
        p: "myWifiPassword"
        c: 13
        h: 0
        r: 1
    CfgWifi:
      type: "object"
      description: "a Wifi STAtion configuration"
      properties:
        n:
          description: "wifi ssid"
          type: "string"
          minLength: 1
          maxLength: 32
        p:
          description: "wifi password"
          type: "string"
          format: "password"
          minLength: 8
          maxLength: 63
    CfgWifis:
      type: "array"
      description: "list of Wifi STAtion configurations"
      items:
        $ref: "#/components/schemas/CfgWifi"
      example: 
        - n: "wifi_ssid1"
          p: "password1"
        - n: "wifi_ssid2"
          p: "password2"
        - n: "wifi_ssid3"
          p: "password3"
    CfgRelay:
      type: "object"
      description: "a relay configuration"
      properties:
        i:
          description: "relay id"
          type: "integer"
          minimum: 0
          maximum: 127
        n:
          description: "relay name"
          type: "string"
          minLength: 1
          maxLength: 32
        a:
          description: "action triggered when a Client joins the AP"
          type: "integer"
          minimum: -1
          maximum: 1
    CfgRelays:
      type: "array"
      description: "list of allowed device configurations"
      items:
        $ref: "#/components/schemas/CfgRelay"
      example: 
        - i: 8
          n: "relay 8"
          a: 1
        - i: 3
          n: "garage"
          a: 0
        - i: 22
          n: "living room"
          a: -1
    ImplRelay:
      type: "object"
      description: "a relay state"
      properties:
        s:
          description: "relay state"
          type: "integer"
          minimum: 0
          maximum: 1
